In [85]:
import pandas as pd
import numpy as np
import zipcodes
import os
import json

from tqdm._tqdm_notebook import tqdm_notebook as tqdm

import plotly.express as px

tqdm.pandas()

/Users/tim/miniconda3/lib/python3.8/site-packages/tqdm/std.py:697: FutureWarning:

The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version

In [9]:
df = pd.read_csv('./capacity.csv')

In [10]:
df.head()

,hospital_pk,collection_week,state,ccn,hospital_name,address,city,zip,hospital_subtype,fips_code,...,previous_day_admission_adult_covid_suspected_30-39_7_day_sum,previous_day_admission_adult_covid_suspected_40-49_7_day_sum,previous_day_admission_adult_covid_suspected_50-59_7_day_sum,previous_day_admission_adult_covid_suspected_60-69_7_day_sum,previous_day_admission_adult_covid_suspected_70-79_7_day_sum,previous_day_admission_adult_covid_suspected_80+_7_day_sum,previous_day_admission_adult_covid_suspected_unknown_7_day_sum,previous_day_admission_pediatric_covid_suspected_7_day_sum,previous_day_total_ED_visits_7_day_sum,previous_day_admission_influenza_confirmed_7_day_sum
0,452193,2020-12-04,TX,452193,El Paso LTAC Hospital,NaN,NaN,79902.0,Long Term,NaN,...,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0
1,ee04edd185865c38c839812cb2eb5ae5d3f8922e3b629e...,2020-12-04,LA,NaN,Alexandria Emergency Hospital,5900 Coliseum Blvd,Alexandria,71303.0,Short Term,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aab2bb3ab769da90baf57242c96ec481afb5ec6a233784...,2020-12-04,LA,NaN,Crescent City Surgical Centre,NaN,NaN,70118.0,Short Term,NaN,...,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0
3,3b081d5ef1c552538e4af4aa593a857bb922a4f364a412...,2020-12-04,LA,NaN,Surgery Center of Zachary,NaN,NaN,70791.0,Short Term,NaN,...,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0
4,f70d7abf93c78280583ac18e896e6737cca8212b017513...,2020-12-04,NV,NaN,Elite Medical Center,150 E Harmon Ave,Las Vegas,89109.0,Short Term,NaN,...,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,-999999.0,92.0,-999999.0

In [4]:
len(df)

92269

In [5]:
df.describe()

,zip,fips_code,total_beds_7_day_avg,all_adult_hospital_beds_7_day_avg,all_adult_hospital_inpatient_beds_7_day_avg,inpatient_beds_used_7_day_avg,all_adult_hospital_inpatient_bed_occupied_7_day_avg,total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg,total_adult_patients_hospitalized_confirmed_covid_7_day_avg,total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg,...,previous_day_admission_adult_covid_suspected_30-39_7_day_sum,previous_day_admission_adult_covid_suspected_40-49_7_day_sum,previous_day_admission_adult_covid_suspected_50-59_7_day_sum,previous_day_admission_adult_covid_suspected_60-69_7_day_sum,previous_day_admission_adult_covid_suspected_70-79_7_day_sum,previous_day_admission_adult_covid_suspected_80+_7_day_sum,previous_day_admission_adult_covid_suspected_unknown_7_day_sum,previous_day_admission_pediatric_covid_suspected_7_day_sum,previous_day_total_ED_visits_7_day_sum,previous_day_admission_influenza_confirmed_7_day_sum
count,92260.000000,92020.000000,90984.000000,86006.000000,86781.000000,91316.000000,88996.000000,90013.000000,89712.000000,89860.000000,...,82407.000000,82651.000000,83001.000000,83466.000000,83383.000000,83173.000000,84747.000000,86134.000000,87807.000000,35497.000000
mean,54125.037329,29430.362899,-6730.732342,-29261.530413,-37501.573129,-92654.205749,-112024.375272,-527401.041835,-574573.443299,-985676.583123,...,-939396.858034,-926787.014507,-879637.986085,-841945.105013,-841991.679851,-852401.668739,-973377.856313,-967688.354448,-119692.433838,-994082.962673
std,26892.188987,16267.766428,82807.967833,168998.988858,190339.154620,290122.042440,315545.341096,499262.018460,494418.896062,118817.423545,...,238601.565921,260486.740046,325386.745459,364795.792258,364752.099596,354704.423979,160976.696109,176826.341077,325290.420571,76689.294816
min,603.000000,1001.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,...,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000
25%,33033.000000,17037.000000,29.300000,27.000000,24.000000,10.000000,9.300000,-999999.000000,-999999.000000,-999999.000000,...,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,64.000000,-999999.000000
50%,55435.000000,29031.000000,76.000000,70.000000,58.000000,35.100000,31.900000,-999999.000000,-999999.000000,-999999.000000,...,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,255.000000,-999999.000000
75%,76132.000000,42091.000000,225.000000,204.000000,172.400000,130.300000,122.400000,13.900000,10.900000,-999999.000000,...,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,-999999.000000,642.000000,-999999.000000
max,99901.000000,78020.000000,5015.400000,4780.000000,2875.400000,2442.400000,2192.700000,929.000000,672.900000,121.900000,...,120.000000,141.000000,163.000000,170.000000,191.000000,161.000000,2066.000000,407.000000,49337.000000,50.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92269 entries, 0 to 92268
Data columns (total 93 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   hospital_pk                                                                         92269 non-null  object
 1   collection_week                                                                     92269 non-null  object
 2   state                                                                               92269 non-null  object
 3   ccn                                                                                 91867 non-null  object
 4   hospital_name                                                                       92269 non-null  object
 5   address                                                                             92115 non-null  object
 6   city                                                                                92134 non-null  object
 7   zip                                                                                 92260 non-null  float64
 8   hospital_subtype                                                                    92269 non-null  object
 9   fips_code                                                                           92020 non-null  float64
 10  is_metro_micro                                                                      92269 non-null  bool
 11  total_beds_7_day_avg                                                                90984 non-null  float64
 12  all_adult_hospital_beds_7_day_avg                                                   86006 non-null  float64
 13  all_adult_hospital_inpatient_beds_7_day_avg                                         86781 non-null  float64
 14  inpatient_beds_used_7_day_avg                                                       91316 non-null  float64
 15  all_adult_hospital_inpatient_bed_occupied_7_day_avg                                 88996 non-null  float64
 16  total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg           90013 non-null  float64
 17  total_adult_patients_hospitalized_confirmed_covid_7_day_avg                         89712 non-null  float64
 18  total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg       89860 non-null  float64
 19  total_pediatric_patients_hospitalized_confirmed_covid_7_day_avg                     89361 non-null  float64
 20  inpatient_beds_7_day_avg                                                            90462 non-null  float64
 21  total_icu_beds_7_day_avg                                                            90117 non-null  float64
 22  total_staffed_adult_icu_beds_7_day_avg                                              85441 non-null  float64
 23  icu_beds_used_7_day_avg                                                             90536 non-null  float64
 24  staffed_adult_icu_bed_occupancy_7_day_avg                                           86666 non-null  float64
 25  staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg                  88211 non-null  float64
 26  staffed_icu_adult_patients_confirmed_covid_7_day_avg                                88047 non-null  float64
 27  total_patients_hospitalized_confirmed_influenza_7_day_avg                           35563 non-null  float64
 28  icu_patients_confirmed_influenza_7_day_avg                                          35525 non-null  float64
 29  total_patients_hospitalized_confirmed_influenza_and_covid_7_day_avg                 35506 non-null  float64
 30  total_beds_7_day_sum                                                                90984 non-null  float64
 31  all_adult_hospital_beds_7_day_sum                                                   86006 non-null  float64
 32  all_adult_hospital_inpatient_beds_7_day_sum                                         86781 non-null  float64
 33  inpatient_beds_used_7_day_sum                                                       91316 non-null  float64
 34  all_adult_hospital_inpatient_bed_occupied_7_day_sum                                 88996 non-null  float64
 35  total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum           90013 non-null  float64
 36  total_adult_patients_hospitalized_confirmed_covid_7_day_sum                         89712 non-null  float64
 37  total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum       89860 non-null  float64
 38  total_pediatric_patients_hospitalized_confirmed_covid_7_day_sum                     89361 non-null  float64
 39  inpatient_beds_7_day_sum                                                            90462 non-null  float64
 40  total_icu_beds_7_day_sum                                                            90117 non-null  float64
 41  total_staffed_adult_icu_beds_7_day_sum                                              85441 non-null  float64
 42  icu_beds_used_7_day_sum                                                             90536 non-null  float64
 43  staffed_adult_icu_bed_occupancy_7_day_sum                                           86666 non-null  float64
 44  staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum                  88211 non-null  float64
 45  staffed_icu_adult_patients_confirmed_covid_7_day_sum                                88047 non-null  float64
 46  total_patients_hospitalized_confirmed_influenza_7_day_sum                           35563 non-null  float64
 47  icu_patients_confirmed_influenza_7_day_sum                                          35525 non-null  float64
 48  total_patients_hospitalized_confirmed_influenza_and_covid_7_day_sum                 35506 non-null  float64
 49  total_beds_7_day_coverage                                                           92269 non-null  int64
 50  all_adult_hospital_beds_7_day_coverage                                              92269 non-null  int64
 51  all_adult_hospital_inpatient_beds_7_day_coverage                                    92269 non-null  int64
 52  inpatient_beds_used_7_day_coverage                                                  92269 non-null  int64
 53  all_adult_hospital_inpatient_bed_occupied_7_day_coverage                            92269 non-null  int64
 54  total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage      92269 non-null  int64
 55  total_adult_patients_hospitalized_confirmed_covid_7_day_coverage                    92269 non-null  int64
 56  total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage  92269 non-null  int64
 57  total_pediatric_patients_hospitalized_confirmed_covid_7_day_coverage                92269 non-null  int64
 58  inpatient_beds_7_day_coverage                                                       92269 non-null  int64
 59  total_icu_beds_7_day_coverage                                                       92269 non-null  int64
 60  total_staffed_adult_icu_beds_7_day_coverage                                         92269 non-null  int64
 61  icu_beds_used_7_day_coverage                                                        92269 non-null  int64
 62  staffed_adult_icu_bed_occupancy_7_day_coverage                                      92269 non-null  int64
 63  staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_coverage             92269 non-null  int64
 64  staffed_icu_adult_patients_confirmed_covid_7_day_coverage                           92269 non-null  int64
 65  total_patients_hospitalized_confirmed_influenza_7_day_coverage                      92269 non-null  int64
 66  icu_patients_confirmed_influenza_7_day_coverage                                     92269 non-null  int64
 67  total_patients_hospitalized_confirmed_influenza_and_covid_7_day_coverage            92269 non-null  int64
 68  previous_day_admission_adult_covid_confirmed_7_day_sum                              90816 non-null  float64
 69  previous_day_admission_adult_covid_confirmed_18-19_7_day_sum                        81099 non-null  float64
 70  previous_day_admission_adult_covid_confirmed_20-29_7_day_sum                        81861 non-null  float64
 71  previous_day_admission_adult_covid_confirmed_30-39_7_day_sum                        82242 non-null  float64
 72  previous_day_admission_adult_covid_confirmed_40-49_7_day_sum                        82434 non-null  float64
 73  previous_day_admission_adult_covid_confirmed_50-59_7_day_sum                        82841 non-null  float64
 74  previous_day_admission_adult_covid_confirmed_60-69_7_day_sum                        83266 non-null  float64
 75  previous_day_admission_adult_covid_confirmed_70-79_7_day_sum                        83332 non-null  float64
 76  previous_day_admission_adult_covid_confirmed_80+_7_day_sum                          83066 non-null  float64
 77  previous_day_admission_adult_covid_confirmed_unknown_7_day_sum                      85152 non-null  float64
 78  previous_day_admission_pediatric_covid_confirmed_7_day_sum                          85934 non-null  float64
 79  previous_day_covid_ED_visits_7_day_sum                                              86383 non-null  float64
 80  previous_day_admission_adult_covid_suspected_7_day_sum                              90732 non-null  float64
 81  previous_day_admission_adult_covid_suspected_18-19_7_day_sum                        80878 non-null  float64
 82  previous_day_admission_adult_covid_suspected_20-29_7_day_sum                        82265 non-null  float64
 83  previous_day_admission_adult_covid_suspected_30-39_7_day_sum                        82407 non-null  float64
 84  previous_day_admission_adult_covid_suspected_40-49_7_day_sum                        82651 non-null  float64
 85  previous_day_admission_adult_covid_suspected_50-59_7_day_sum                        83001 non-null  float64
 86  previous_day_admission_adult_covid_suspected_60-69_7_day_sum                        83466 non-null  float64
 87  previous_day_admission_adult_covid_suspected_70-79_7_day_sum                        83383 non-null  float64
 88  previous_day_admission_adult_covid_suspected_80+_7_day_sum                          83173 non-null  float64
 89  previous_day_admission_adult_covid_suspected_unknown_7_day_sum                      84747 non-null  float64
 90  previous_day_admission_pediatric_covid_suspected_7_day_sum                          86134 non-null  float64
 91  previous_day_total_ED_visits_7_day_sum                                              87807 non-null  float64
 92  previous_day_admission_influenza_confirmed_7_day_sum                                35497 non-null  float64
dtypes: bool(1), float64(65), int64(19), object(8)
memory usage: 64.9+ MB

In [8]:
df.filter(like="total_patients_hospitalized_confirmed_influenza_and_covid_7").describe()

,total_patients_hospitalized_confirmed_influenza_and_covid_7_day_avg,total_patients_hospitalized_confirmed_influenza_and_covid_7_day_sum,total_patients_hospitalized_confirmed_influenza_and_covid_7_day_coverage
count,35506.000000,35506.000000,92269.000000
mean,-985719.525317,-956849.888385,2.445448
std,118643.017817,203199.171939,3.222408
min,-999999.000000,-999999.000000,0.000000
25%,-999999.000000,-999999.000000,0.000000
50%,-999999.000000,-999999.000000,0.000000
75%,-999999.000000,-999999.000000,7.000000
max,70.900000,496.000000,7.000000

In [23]:
def map_zipcode_to_coords(zipcode):
    try:
        zip_results = zipcodes.matching(str(int(zipcode)).zfill(5))
        return float(zip_results[0]['lat']), float(zip_results[0]['long'])
    except:
        print(f"No Match: {zipcode}")
        return -1, -1


df['lat'], df['lng'] = zip(*df['zip'].progress_apply(map_zipcode_to_coords))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=92269.0), HTML(value='')))

No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: 72405.0
No Match: nan
No Match: 72405.0
No Match: nan
No Match: 72405.0
No Match: nan
No Match: nan
No Match: 72405.0
No Match: nan
No Match: 72405.0
No Match: nan
No Match: 72405.0
No Match: nan
No Match: 72405.0
No Match: nan
No Match: 72405.0
No Match: nan
No Match: 72405.0

In [139]:
variable_one = 'inpatient_beds_used_7_day_avg'
variable_two = 'inpatient_beds_7_day_avg'

df_map = df[df['lat'] > 0]
# df_map = df_map[df_map['collection_week'] == '2020-12-04']
df_map = df_map[df_map['inpatient_beds_used_7_day_avg'] >= 0]
df_map = df_map[df_map['inpatient_beds_7_day_avg'] >= 0]
df_map['proportion_used'] = ((df_map['inpatient_beds_used_7_day_avg'] / df_map['inpatient_beds_7_day_avg']) * 100).astype(int)
df_map['zip'] = df_map['zip'].apply(lambda zipcode: str(int(zipcode)).zfill(5))
df_map = df_map.sort_values(by=['collection_week'])

len(df_map)

81918

In [133]:
df_map['collection_week'].unique()

array(['2020-07-31', '2020-08-07', '2020-08-14', '2020-08-21',
       '2020-08-28', '2020-09-04', '2020-09-11', '2020-09-18',
       '2020-09-25', '2020-10-02', '2020-10-09', '2020-10-16',
       '2020-10-23', '2020-10-30', '2020-11-06', '2020-11-13',
       '2020-11-20', '2020-11-27', '2020-12-04'], dtype=object)

In [1]:
# fig = px.density_mapbox(df_map, lat='lat', lon='lng',
#                         z='proportion_used',
#                         radius=10,
#                         hover_name='hospital_name',
#                         range_color=[0, df_map['proportion_used'].max()],
#                         animation_frame="collection_week",
#                         center=dict(lat=37.0902, lon=-95.7129), zoom=2.5,
#                         mapbox_style="stamen-terrain")
# fig.show()

In [2]:

# df_map_ca = df_map[df_map['state'] == 'CA']
# fig = px.choropleth_mapbox(df_map_ca, geojson=california,
#                            locations='zip',
#                            featureidkey='properties.ZCTA5CE10',
#                            color='proportion_used',
#                            color_continuous_scale="Viridis",
#                            mapbox_style="carto-positron",
#                            zoom=3, center = {"lat": 37.0902, "lon": -95.7129},
#                            opacity=0.5,
#                           )
# fig.show()

In [86]:
with open('./data/geojsons/CA.json') as file:
    california = json.load(file)

In [107]:
california['features'][0]['properties']['ZCTA5CE10']

'94601'

In [108]:
df_map_ca['zip']

278    94538.0
279    94538.0
280    94577.0
281    94611.0
282    94545.0
        ...
626    93010.0
627    93030.0
628    95616.0
629    95695.0
630    95901.0
Name: zip, Length: 338, dtype: object

In [ ]:
df['']